lightcopy/parquet-index

- README.md
- src/main/scala/org/apache/spark/sql/DataFrameIndexManager.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/IndexedDataSource.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/MetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtils.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/main/scala/org/apache/spark/sql/internal/IndexConf.scala
- src/test/scala/org/apache/spark/sql/DataFrameIndexManagerSuite.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtilsSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDDSuite.scala
This PR adds option to create index if one does not exist yet in metastore, when querying table. Use `spark.sql.index.createIfNotExists` to specify whether or not you want this behaviour, by default option is `false`.
PR slightly changes internal behaviour, now empty sequence of columns is treated as `all available for index` columns. Previously this would throw exception of empty schema. Again this is done at implementation level, but I added API note saying that this behaviour should be supported.
> Create index if it does not exist when querying table

- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/statistics.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDDSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/StatisticsSuite.scala
This PR fixes bug when indexing column that has all null values by introducing `ParquetNullStatistics` and updating `convertStatistics` method. Also added 2 tests on correctness for all nulls column filtering and querying when expected 0 rows.
> Fix null statistics issue

- build.sbt
- src/main/scala/org/apache/spark/sql/execution/datasources/Metastore.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreSuite.scala
This PR adds cache for metastore, so every index catalog is cached after first load. This allows to minimize time when querying table very frequently. Currently metastore cache (essentially per Spark session) only holds 16 index catalogs and each entry expires after 12 hours, and these numbers are not configurable.
> Cache support for metastore

- .travis.yml
- README.md
- src/main/scala/org/apache/spark/sql/execution/datasources/IndexedDataSource.scala
This PR adds Spark 2.0.0 using reflection. The only change is parameter list when instantiating `HadoopFsRelation`, so we reorder parameters based on version. Also added Spark 2.0.0 build into `.travis.yml`.
TODOs:
> Add Spark 2.0.0 support

- README.md
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexCatalog.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexFilters.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/main/scala/org/apache/spark/sql/internal/IndexConf.scala
- src/main/scala/org/apache/spark/sql/sources/ColumnFilterStatistics.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexFiltersSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupportSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDDSuite.scala
- src/test/scala/org/apache/spark/sql/sources/ColumnFilterStatisticsSuite.scala
This PR refactors `ParquetStatisticsRDD` for easy filter statistics addition of new types by implementing new case in `newFilter(...)` method. This results in new configuration options being introduced:
- `spark.sql.index.parquet.filter.enabled` - whether or not filter enabled, default is `false`
- `spark.sql.index.parquet.filter.type` - what type of filters to use, default is `bloom`
- `spark.sql.index.parquet.filter.eagerLoading` - whether or not load all filters when reading catalog, default is `false` which is 0.1.0 behaviour
Old option `spark.sql.index.parquet.bloom.enabled` for bloom filters does not take effect anymore, so it is recommended to switch to new options.
PR also optimises index filters resolution and statistics loading by removing dependency on `Configuration`. In case …
> Column filter statistics loading

- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexCatalog.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexFilters.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexCatalogSuite.scala
As per #40, querying table would fail, if table has empty partitions, e.g. Parquet table has empty files on disk. In this case Parquet file has 0 block metadata chunks, because there is no data. But in the code we explicitly check for `ParquetFileStatus` to have non-empty blocks, which correspond to block metadata chunks, which fails requirement for empty partitions. 
This PR fixes the problem by removing check and updating `ParquetIndexFilters` to handle empty blocks. Current approach is returning `Trivial(false)` if empty blocks are provided, because file is empty so all predicates will be evaluated to `false`.
> Fix issue with empty blocks

- README.md
- src/main/scala/org/apache/spark/sql/internal/IndexConf.scala
This PR updates filter statistics option to be `true` by default, which means users will get better performance out of the box. It can be marked as stable considering results of manual and unit tests.
> Enable filter statistics by default

- README.md
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/main/scala/org/apache/spark/sql/internal/IndexConf.scala
- src/main/scala/org/apache/spark/sql/sources/ColumnFilterStatistics.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDDSuite.scala
- src/test/scala/org/apache/spark/sql/sources/ColumnFilterStatisticsSuite.scala
This PR adds dictionary filter statistics that are based on `java.util.HashSet`. Now user can choose between `bloom` (Bloom filter statistics) and `dict` (Dictionary filter statistics) when creating index. 
Also added/updated filter statistics tests and read correctness tests.
Benchmarks on test dataset of 1,000,000 records with simple `Or(EqualTo(code,2),EqualTo(code,120))` query shows that with bloom filter statistics Spark would scan ~8 files. Same dataset with same filter and dictionary filter statistics would read only 2 files (both codes are in different files).
Dictionary filters are slower (x2) to create than bloom filters, and they take more space, stats below for sample dataset:
```
bloom filters:
total: 6.6M
metadata: 300K
filter file: 2.2K
dict filters:
total: 16M
metadata: …
```
> Add dictionary filter statistics

- src/main/scala/org/apache/spark/sql/execution/datasources/IndexSourceStrategy.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDDSuite.scala
This PR overrides preferred locations method in `ParquetStatisticsRDD` similar to `FileScanRDD` in Spark. This work is based on PR 12527. The main difference is `FileScanRDD` selects host with max bytes available, we currently do not have that logic and return all hosts in `SerializableFileStatus`.
Closes #49.
> Add preferred locations for ParquetStatisticsRDD

- README.md
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexReadSupport.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtils.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/main/scala/org/apache/spark/sql/sources/ColumnFilterStatistics.scala
- src/main/scala/org/apache/spark/sql/sources/ColumnStatistics.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexReadSupportSuite.scala
- src/test/scala/org/apache/spark/sql/sources/ColumnFilterStatisticsSuite.scala
- src/test/scala/org/apache/spark/sql/sources/ColumnStatisticsSuite.scala
This PR adds support for `DateType` and `TimestampType` SQL column types by adding new statistics types and updating filter statistics to handle `java.sql.Date` and `java.sql.Timestamp`. 
Also update behaviour of processing values of unmatched type for column statistics. Before this patch, those values were ignored, after - exception will be thrown.
> DateType and TimestampType support

- src/main/scala/org/apache/spark/sql/execution/datasources/IndexSourceStrategy.scala
This PR adds warning that is triggered when indexed filters are empty. This can be caused by either using non-indexed columns or some predicates where it is impossible to evaluate indexed columns separately without reading full table.
Closes #53.
> Add warning when querying with non-indexed columns

- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtils.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/metadata.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupportSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtilsSuite.scala
This PR fixes bug when merging Parquet schema, it would leave field metadata out, which results in inconsistency in schema between `spark.read.parquet` and `spark.index.parquet`. This issue was found when trying to index persistent tables. 
The implementation is slightly different from Spark. Instead of just fetching the first SQL schema from footer metadata, we parse all of them and try to merge `StructType`s including metadata.
> Extract metadata when inferring schema

- README.md
- python/src/lightcopy/index.py
- src/main/scala/org/apache/spark/sql/DataFrameIndexManager.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/CatalogTableSource.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/IndexLocationSpec.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/IndexedDataSource.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/Metastore.scala
- src/test/java/com/github/lightcopy/api/JavaApiSuite.java
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/CatalogTableSourceSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/IndexLocationSpecSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/IndexedDataSourceSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupportSuite.scala
This PR adds support for Spark persistent tables that are created with `saveAsTable`, only Parquet format is supported. Implementation introduces `CatalogTableSource` that parses table name and extracts information, including warehouse path for actual files. `CatalogTableSource` is then converted into `IndexedDataSource` and indexed similar to datasource tables.
PR introduces breaking change by adding identifier to metastore, to separate catalog tables from source tables and potentially other sources, meaning indexes that were created **before this patch** will not be read, and will require to recreate index for those tables.
Features like Python API and merging path into metastore identifier will be done in separate PRs.
> Persistent table support

- README.md
- python/src/lightcopy/index.py
- python/test/test_index.py
This PR adds Python API in addition to Java and Scala APIs for indexing catalog tables.
> Python API for persistent tables

- src/main/scala/org/apache/spark/sql/execution/datasources/IndexLocationSpec.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/IndexedDataSource.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/Metastore.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/IndexLocationSpecSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/IndexedDataSourceSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupportSuite.scala
This PR updates `IndexLocationSpec` to include source path. Before this patch, path was propagated separately into metastore, after - we include it into location spec when creating it. Therefore metastore only requires location spec to create/load/delete/check index, which makes it easier to extend it with metadata, etc.
> Update location spec

- src/main/scala/org/apache/spark/sql/execution/datasources/Metastore.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreSuite.scala
This PR updates metastore permissions from `rwxrw-rw-` to `rwxr--r--`, which is more suitable when it is manually created, and also avoids error in #67.
Fixes #67.
> Update metastore permissions

- README.md
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/internal/IndexConf.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupportSuite.scala
This PR adds option `spark.sql.index.partitions` to provide number of partitions that should be used when creating index or other `sc.parallelize` code. Also changes default value to be `sc.defaultParallelism * 3` instead of 2.
> Index number of partitions

- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtils.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaUtilsSuite.scala
This PR fixes error message in `ParquetMetastoreSupport`, so now it shows the original schema and indexed column that does not exist - easier to check original schema. Also wraps column names in messages with quotes.
Closes #71.
> Fix error message when no columns found in schema

- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexCatalog.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupport.scala
This PR updates code for sequential resolution of `foldFilter` by using futures and executing `resolveSupported` method in parallel for each file in Parquet partition; partitions are still resolved sequentially. 
Manual testing shows about 1.5-2x performance improvement when filtering index partitions (with large portion of files being scanned). But it also introduces a little bit of overhead when filtering partitions on cached index (20ms vs 35ms). This approach is similar to eager loading.
Benchmarks:
Each test includes cold start and warm start (same query but all necessary column filters have been loaded on previous step)
`master`
```
Applying index filters: IsNotNull(strid),EqualTo(strid,35732)
Filtered indexed partitions in 438.53 ms
Post-Scan filters: isnotnull(strid#13),(strid#13 …
```
> Improve pruneIndexedPartitions by using futures

- .travis.yml
- README.md
- bin/setup-spark
- build.sbt
- src/main/scala/org/apache/spark/sql/execution/datasources/CatalogTableSource.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/IndexSourceStrategy.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/IndexedDataSource.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/Metastore.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/MetastoreIndex.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/MetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndex.scala
- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupport.scala
- src/main/scala/org/apache/spark/sql/internal/IndexConf.scala
- src/main/scala/org/apache/spark/sql/sources/filters.scala
- src/test/scala/org/apache/spark/sql/IndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/CatalogTableSourceSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/IndexedDataSourceSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreIndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/MetastoreSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexFiltersSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexReadSupportSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetIndexSuite.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetMetastoreSupportSuite.scala
This PR adds support for Spark 2.2+. 
I will add Spark 2.1 support separately, because of some method signature changes, that I do not want to cover with reflection.
Closes #77 
Closes #78
> Spark 2.2 support

- src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDD.scala
- src/test/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetStatisticsRDDSuite.scala
Added static getFS to check for null and non-null default URI
Added basic test on file:// (couldn't add s3a due to credentials and aws classes)
> ISSUE 86: Creating Hadoop FS based on URI and conf

- README.md
- python/run_tests.py
- python/src/lightcopy/index.py
- python/test/__init__.py
- python/test/test_index.py
This patch adds support for python 3, but deprecates python 2 at the moment.
One could achieve a better result by using the `six` library, or some `from __future__ import print` magic, but it's also true that Python 2 is officially in EOL since January 1, 2020.
I used the 2to3 tool to convert the code and so far it seems to work.
> Add support for python 3, deprecate python 2
